### ISSUE TITLE
calling policy via Postman

### ISSUE THREAD

**Issue by mauricioOrihuelaCpb** [azure-ad-b2c/samples#327] opened 2021-12-03 15:38 UTC
I got your fantastic custom policy to work but I would like to call it via Postman. 

On the past I was able to call a policy by doing an http POST to  https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/oauth2/v2.0/token?p=My_policy

Is it possible to do that with your custom policy? 

Thanks, Mauricio

**Comment by JasSuri** [comment] 2021-12-04 09:38
Only ROPC policy can be called in this way. 
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=app-reg-ga&pivots=b2c-custom-policy

All policies in this repo are interactive policies, which call /authorize endpoint then /token endpoint.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/openid-connect

Closing as this is not a bug with any policy here.

**Closed by JasSuri** 2021-12-04 09:38 UTC
