### ISSUE TITLE
Unable to add Apple as identity provider per the sample

### ISSUE THREAD

**Issue by mtanml** [azure-ad-b2c/samples#20] opened 2019-10-07 14:46 UTC
I'm following the instructions at https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-apple to add "Sign in with Apple" as a B2C identity provider.

I got to the very last step, and when I click Save I get the error "The issuer 'https://appleid.apple.com' found at the metadata endpoint _{my endpoint}_ is already in use by an identity provider.

Are those instructions still valid?

**Comment by otsomkalov** [comment] 2019-10-31 11:54
Facing the same issue. Any updates?

**Comment by JasSuri** [comment] 2019-11-06 21:01
Looking into it for you.

**Comment by 1iveowl** [comment] 2019-11-15 17:10
Any update here? I'm facing the same issue as outlined above.

**Comment by 1iveowl** [comment] 2019-11-21 09:51
Added a StackOverflow question on this in hope that progress will be made on this: [Sign in with Apple guide - the metadata endpoint is already in use by an identity provider](https://stackoverflow.com/questions/58971848/sign-in-with-apple-guide-the-metadata-endpoint-is-already-in-use-by-an-identit)

**Comment by agrabhi** [comment] 2019-11-21 17:49
Answered in SO.

**Comment by alanwoolley** [comment] 2019-11-25 14:30
I'm also getting the same error despite not having a custom identity provider with the same issuer. If I change the issuer in my `.well-known/openid-configuration` file in any way, keeping the rest of the configuration the same, I can create a new provider.

**Comment by JasSuri** [comment] 2019-11-25 14:33
There appears to be an issue here in regards to the conflict with the metadata endpoint, we are working on it.

**Comment by abastias** [comment] 2019-11-28 00:57
I am having the same problem... 
The issuer 'https://appleid.apple.com' found at the metadata endpoint '{My azure function}/.well-known/openid-configuration' is already in use by an identity provider.

Apple rejected my app because they want me to include "Sing in with Apple"

Any help will be very welcome.

**Comment by agrabhi** [comment] 2019-12-07 06:08
The issue is resolved now.

**Comment by WhippsP** [comment] 2019-12-17 07:34
Closing as per @agrabhi request.

**Closed** 2019-12-17 07:33 UTC

**Comment by wojtekdo** [comment] 2020-01-13 11:31
This fixed the problem for a single Apple ID provider. I need more of them and adding any consecutive gives me the same error.
I have many apps in different Apple developer accounts, with different services configured (different client Ids) and need users in a single AAD B2C tenant. IEF seems to enable this approach but not standard policies and I need them in a few places where exchanging policy to a custom one would be very difficult.

**Comment by agrabhi** [comment] 2020-01-13 17:22
That's by design in basic policies 

Azure AD B2C enforces the distinct issuer. The reason being that unique id of the user depends on the client Id in that system. If you have two apps in Facebook, Facebook will give you separate unique user Id for same user using different apps. So AADB2C wants that connection to one issuer is established through only one identity provider.

Any reason why you would want to use the same tenant?
