### ISSUE TITLE
banned-password-list-no-API

### ISSUE THREAD

**Issue by rprohit66** [azure-ad-b2c/samples#100] opened 2020-08-11 19:06 UTC
I am using the Base and Extension Files from the  [SocialAndLocalAccounts starter pack](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/SocialAndLocalAccounts) mentioned in the Sample and then using the files mentioned in the policy folder (**samples/policies/banned-password-list-no-API**). After that I executed the SignUpSignIn Flow and used the Weak Password and getting the error message of Weak Password as shown in below screenshot, but I observed that account is also created which shouldn't be the case and Password getting changed on the account while using Password Reset flow. 

Let me know if you are also getting the same executing it or am I missing something.

![image](https://user-images.githubusercontent.com/41752010/89937290-83724100-dc32-11ea-8d0e-add2ebce8f02.png)

**Comment by rprohit66** [comment] 2020-08-24 10:55
Password is getting changed even if I am getting the above error which shouldn't be the case, if the password is weak it just give the error. Is this what we are expecting.Right?

**Comment by neilD2** [comment] 2020-10-08 08:46
I get the same issue

**Comment by JasSuri** [comment] 2020-10-08 08:56
Following my logic through

```xml
<ValidationTechnicalProfile ReferenceId="AAD-UserWritePasswordUsingObjectId">
  <Preconditions>
    <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
      <Value>banned</Value>
      <Value>True</Value>
```

#### The password is only written if:
1. `banned` -> is uninitialized -> which it should never be since `CheckBannedPasswordValue` is always run via `PasswordReset-CheckPwdEquivalenceAndBannedList` and outputs a boolean.
2. `banned` -> False

Can you check what the value of "banned" is in the custom policy App Insights logs?
https://docs.microsoft.com/en-us/azure/active-directory-b2c/troubleshoot-with-application-insights

**Comment by JasSuri** [comment] 2020-10-08 09:01
I've confirmed in my env, i cannot reproduce this issue. Waiting on logs from you both.

**Comment by neilD2** [comment] 2020-10-08 21:29
Hi @JasSuri , I think it's because I removed the Preconditions blocks, as they are not allowed to be in the ValidationTechnicalProfile schema, any work arounds? Thanks.

**Comment by JasSuri** [comment] 2020-10-08 22:21
I don’t understand, the policy is valid as-is and should upload fine. Can you configure it as the sample and let me know if there is an error uploading it (and what the error is). 

Removing the preconditions would explain the behaviour....

**Comment by neilD2** [comment] 2020-10-09 07:58
I checked in the http://schemas.microsoft.com/online/cpim/schemas/2013/06, and couldn't see a reference to preconditions in the ValidationTechnicalProfile element, only in the OrchestrationStep..

Here is the validation error:

Validation failed: 1 validation error(s) found in policy "B2C_1A_TRUSTFRAMEWORKBASE" of tenant "devtestsolutions.onmicrosoft.com".Schema validation error found at line 649 col 14 in policy "B2C_1A_TRUSTFRAMEWORKBASE" of tenant "devtestsolutions.onmicrosoft.com": The element 'ValidationTechnicalProfiles' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06' has invalid child element 'Preconditions' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06'. List of possible elements expected: 'ValidationTechnicalProfile' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06'.Schema validation error found at line 649 col 14 in policy "B2C_1A_TRUSTFRAMEWORKBASE" of tenant "devtestsolutions.onmicrosoft.com": The element 'ValidationTechnicalProfiles' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06' has invalid child element 'Preconditions' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06'. List of possible elements expected: 'ValidationTechnicalProfile' in namespace 'http://schemas.microsoft.com/online/cpim/schemas/2013/06'.

**Comment by JasSuri** [comment] 2020-10-09 08:11
We definitely support it, a ton of samples rely on it.
Can you also paste the section of XML the error is pointing to?

**Comment by neilD2** [comment] 2020-10-09 09:35
<ValidationTechnicalProfiles>
            <ValidationTechnicalProfile ReferenceId="PasswordReset-CheckPwdEquivalenceAndBannedList" />
            <ValidationTechnicalProfile ReferenceId="AAD-UserWritePasswordUsingObjectId">
              <Preconditions>
                <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
                  <Value>banned</Value>
                  <Value>True</Value>
                  <Action>SkipThisValidationTechnicalProfile</Action>
                </Precondition>
              </Preconditions>
            </ValidationTechnicalProfile>
          </ValidationTechnicalProfiles>
        </TechnicalProfile>

**Comment by JasSuri** [comment] 2020-10-09 10:46
That looks fine. The error is stating that you have `Preconditions` under the node `ValidationTechnicalProfiles`, **which is not the case in that snippet**. Maybe check the rest of your file, and maybe its a line break or end tag issue somewhere.

**Closed** 2020-11-26 14:21 UTC
