### ISSUE TITLE
Add "Sign In with Authenticator" link in a self-asserted page

### ISSUE THREAD

**Issue by pnjsatpathy** [azure-ad-b2c/samples#265] opened 2021-08-05 16:03 UTC
Hello,

I am using a custom policy with three sign-in options(Phone/Email/username). I have referred this "https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/scenarios/phone-number-passwordless"  starterpack  to build my custom policy.
![image](https://user-images.githubusercontent.com/83345963/128378298-292166d6-6f8b-4727-85c6-16856048def8.png)

Now I want to add a "**Sign in with authenticator**" link in the 2nd page which is a **selfasserted** page. When user will enter his email address and click on continue on the 1st page then he should be able to see the below screen along with the "**Sign in with Authenticator**" at the bottom. User has to choose whether he/she wants to go with password login or want to go with Authenticator  app (Password-less).
![image](https://user-images.githubusercontent.com/83345963/128379610-34b1bc89-e2f3-4cf5-9c25-32459a9cd562.png)

I merged the changes that are part of https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-authenticator starterpack to my TrustFrameworkBase.xml and SignuporSignin.xml. But this is not what exactly I want. I don't want "**Sign in with Authenticator**" functionality to be in the 1st signup/sign-in page.

Can anyone tell me whether this solution is achievable through AAD B2C or not ? If yes, please suggest me a way to make it possible.

Thank you,
Nikita.

**Comment by JasSuri** [comment] 2021-08-05 18:36
The way to do this is to mimic how social IDPs work. 

```xml
      <OrchestrationSteps>
      
        <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
          <ClaimsProviderSelections>
            <ClaimsProviderSelection TargetClaimsExchangeId="FacebookExchange" />
         <ClaimsProviderSelections>
            <ClaimsProviderSelection TargetClaimsExchangeId="AuthenticatorExchange" />
            <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
          </ClaimsProviderSelections>
          <ClaimsExchanges>
            <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>

        <!-- Check if the user has selected to sign in using one of the social providers -->
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="FacebookExchange" TechnicalProfileReferenceId="Facebook-OAUTH" />
            <ClaimsExchange Id="AuthenticatorExchange" TechnicalProfileReferenceId="Authenticator-TP" />
            <ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
```

Then you would use JS/CSS to move the button to a hyperlink style.

**Comment by JasSuri** [comment] 2021-08-05 18:40
As this is not a bug with any policy in this repo, I’ll close this, use stackoverflow for design help with [azure-ad-b2c] tag.

**Closed by JasSuri** 2021-08-05 18:40 UTC
