### ISSUE TITLE
Unhandled Bad Request when Login Page is left open

### ISSUE THREAD

**Issue by ps-weber** [azure-ad-b2c/samples#72] opened 2020-05-14 10:09 UTC
see: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/35686603-unhandled-bad-request-when-login-page-is-left-open

This happens with the Standard "Sign in v2" flow. The issue on the feedback site has been open since October 10, 2018.

**Comment by JasSuri** [comment] 2020-05-15 22:04
Closing as this is a duplicate of the user voice feedback which is the correct channel. Not related to a specific sample on this repo.

**Closed by JasSuri** 2020-05-15 22:04 UTC
