### ISSUE TITLE
Unable to customize token with custom claims for application objects (not user objects) in Azure AD B2C

### ISSUE THREAD

**Issue by svirchenko** [azure-ad-b2c/samples#483] opened 2022-11-30 12:46 UTC
I would like to customize token with custom claims for **application objects** (not user objects) in Azure AD B2C.

Currently there is a way to extend application object with **directory extensions** by using Graph API according to docs https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=http#directory-azure-ad-extensions. But there is a problem to include directory extensions on application objects in the token claims for Azure B2C

According to documentation looks like there is no ability to do customize token for application objects in Azure B2C

- Directory extensions are an **Azure AD-only feature** (https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-directory-extension-optional-claims)
- **Only extension attributes on user objects** can be used for emitting claims to applications. (https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-schema-extensions)
Is there any way to include directory extensions in the token claims for Azure B2C applications?

**Comment by JasSuri** [comment] 2022-12-01 13:39
There is no way to include directory extensions in the token claims for Azure B2C applications.
I will close this, as this is not a bug with any sample here.

**Closed by JasSuri** 2022-12-01 13:39 UTC
